version: '3'

dotenv: [".env"]

tasks:
  postgres:
    cmds:
      - docker run --name postgres -p 5432:5432 -e POSTGRES_USER=$KVAPI_DB_USER -e POSTGRES_PASSWORD=$KVAPI_DB_PASS -d postgres:alpine

  createdb:
    cmds:
      - docker exec -it postgres createdb --username=$KVAPI_DB_USER --owner=$KVAPI_DB_USER $KVAPI_DB_NAME

  dropdb:
    cmds:
      - docker exec -it postgres dropdb $KVAPI_DB_NAME

  migrateup:
    cmds:
      - migrate -path db/migrations -database "postgresql://$KVAPI_DB_USER:$KVAPI_DB_PASS@$KVAPI_DB_HOST:$KVAPI_DB_PORT/$KVAPI_DB_NAME?sslmode=$KVAPI_DB_SSL" -verbose up

  migratedown:
    cmds:
      - migrate -path db/migrations -database "postgresql://$KVAPI_DB_USER:$KVAPI_DB_PASS@$KVAPI_DB_HOST:$KVAPI_DB_PORT/$KVAPI_DB_NAME?sslmode=$KVAPI_DB_SSL" -verbose down

  migrateup1:
    cmds:
      - migrate -path db/migrations -database "postgresql://$KVAPI_DB_USER:$KVAPI_DB_PASS@$KVAPI_DB_HOST:$KVAPI_DB_PORT/$KVAPI_DB_NAME?sslmode=$KVAPI_DB_SSL" -verbose up 1

  migratedown1:
    cmds:
      - migrate -path db/migrations -database "postgresql://$KVAPI_DB_USER:$KVAPI_DB_PASS@$KVAPI_DB_HOST:$KVAPI_DB_PORT/$KVAPI_DB_NAME?sslmode=$KVAPI_DB_SSL" -verbose down 1

  psql:
    cmds:
      - docker exec -it postgres psql -U $KVAPI_DB_USER $KVAPI_DB_NAME

  jet:
    cmds:
      - jet -dsn=postgresql://$KVAPI_DB_USER:$KVAPI_DB_PASS@$KVAPI_DB_HOST:$KVAPI_DB_PORT/$KVAPI_DB_NAME?sslmode=$KVAPI_DB_SSL -schema=public -path=./db/gen
